### ISSUE TITLE
oneOf check if only one schema applies should sometimes be ignored if a custom type format is missing

### ISSUE THREAD

**Issue by pjordaan** [thephpleague/openapi-psr7-validator#178]
Imagine an OpenAPI schema with a oneOf linking to 2 string definitions and a custom format:
```
schema:
  oneOf:
    -
      type: string
      format: custom-format
    -
      type: string
      format: another-custom-format
```

With the OpenAPI PSR7 validator this will invalidate that 2 schemas are matched unless I provided a custom format validator (as written in the documentation https://github.com/thephpleague/openapi-psr7-validator#custom-type-formats). Shouldn't this be ignored if no custom type format is provided? Or maybe some warning/configurable setting?
