### ISSUE TITLE
Ensure additionalProperty uses correct schema

### ISSUE THREAD

**Issue by fiasco** [thephpleague/openapi-psr7-validator#190]
I opened PR #187 to address this. Reposting here:

I encountered this issue when attempting to validate data against this schema:

```yaml
EnvironmentFlags:
      type: object
      description: An array of various flags that indicate functionality associated with the environment.
      additionalProperties:
        type: object
        properties:
          cde:
            type: boolean
            description: Determines if the environment is on-demand.
```

The `Properties::validate()` method currently attempts to validate `additionalProperties` by their parent definition which results in an error which validating valid data.
