### ISSUE TITLE
Correct use of this package or not?

### ISSUE THREAD

**Issue by akshare** [thephpleague/openapi-psr7-validator#224]
I'm in the process of testing this package to validate user input for an API.

In my openapi spec, I have enum set with a default value.

```
parameter: sort
    name: sort
    in: query
    description: 'Sort by field'
    required: false
    schema:
        type: string
        default: name
        enum:
           - name
           - id
```

I'm expecting empty/null values sent from query param to be replaced by the default value set in the spec.
Or does this go beyond this packages scope?

Thank you
