### ISSUE TITLE
Dictionary's are not currently supported although openapi v3 supports them

### ISSUE THREAD

**Issue by rlweb** [thephpleague/openapi-psr7-validator#98]
It seems OpenAPI v3 supports dictionaries as shown here: https://swagger.io/docs/specification/data-models/dictionaries/

Here is an example valid schema:
```
type: object
additionalProperties: false
properties:
  identifiers:
    description: Identifiers
    type: array
    items:
      type: object
      additionalProperties:
        type: string
        maxLength: 128
        nullable: true
      example:
        ean: "5039314069422"
        sku: SKU001
```

The above currently doesn't work due to the ArrayHelper::isAssoc call here: https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/Schema/Keywords/Type.php#L49

I'll try and have a go at creating a PR for this! I'll let you know how I get on

Thanks for the great package btw!

**Comment by scaytrase** [comment]
> Here is an example valid schema:

The problem is that your example is invalid schema. `type: string` cannot have `additionalProperties` set. Only `object` can have this (since only `object`) have `properties` at all.

https://swagger.io/docs/specification/data-models/data-types/#free-form

Even in the docs you linked there is no such example with string and additional properties. The schema you are trying to write is


```yaml
type: object
additionalProperties: false
properties:
  identifiers:
    description: Identifiers
    type: object
    additionalProperties:
        type: string
    example: 
      ean: "5039314069422" 
      sku: ajksdhakjdhsak
```

This exact example actually is at the end of page you linked https://swagger.io/docs/specification/data-models/dictionaries/


this will allow
```json
{
  "identifiers": {
    "ean": "5039314069422",
    "sku": "ajksdhakjdhsak",
    "other": "some other identifier"
  }
}
